### ISSUE TITLE
How fast should we go?

### ISSUE THREAD

**Issue by yuxiliu-anu** [semorrison/2017-summer-students#20]
What is the expected speed of working on the project? I don't know how to measure speed, other than maybe time spent on it daily.

After fighting the Lean prover for the last week I felt rather bitter about how hard it is to prove even the most obvious statements. Making any substantial progress will take a lot of time, that I could spend by learning other maths and wait for the experts to improve the provers.

**Comment by felicitylu** [comment]
I am trying to catch up a bit over the weekend, gradually going over Chpt.3 of the online tutorials right now. I tried to jump over some stuff and read the link of self-defining natural numbers... Understanding it was not a very hard task, but establishing the proof on my own was kinda impossible without more readings. 
I do not know what others reckon but I am okay with my speed currently. I plan to spend some time on category theory every day as well. Hopefully in a few days I could give a shot to the projects in our repository...

This might a question to Scott, do you expect us to get some actual findings this summer or just go with our own pace and learn something new? I was not really bothered but Yuxi seemed to be way ahead of me and a bit worried about it...

**Comment by semorrison** [comment]
Hi Yuxi, Fei,

It's certainly true that interactive theorem proving is very difficult, at this point in time! Nevertheless, my experience so far is that while the learning curve is pretty brutal at first, it does start to feel easier as you get some practice.

Certainly from the point of view of learning maths --- yes, you should absolutely not be using an interactive theorem prover, and just read and do stuff!

On the other hand, I think that interactive theorem provers are going to (gradually) get better and more usable, and we're at a critical point now where I think it's useful for mathematicians to be learning how to use them. Both to get a head start on everyone else, but also to push the interactive theorem proving communities "in the right direction" --- they are largely dominated by computer scientists, rather than mathematicians, so I think it's helpful that mathematicians' voices are heard during the development.

I don't have strong expectations about where everyone will get up to over the summer. In particular, if people over time become fed up with Lean, that's an okay outcome, and we can find other things to do.

On the other hand, hopefully some outcomes might include:
1) Having some useful code to contribute to `mathlib`. (e.g. about number theory, combinatorics, or basic representation theory)
2) Writing a report describing some small library written for Lean.
3) Writing a report describing dependent type theory, and how it is used in Lean (although as this is itself not well documented, explaining how dependent type theory and the 'calculus of constructions' are used in Coq).
4) Writing a tactic that reduces the painfulness of proving statements in some domain, and writing a report explaining what went into constructing that tactic.

best regards,
Scott

**Comment by yuxiliu-anu** [comment]
Today I spent a lot of time proving completely trivial things in propositional logic.

In summary, these things were usually of this kind:

For example, in tactic mode, the target goal is
`p or q`
with `p, q, r` being some complicated expressions.
Now, I have proven 
```
p or q or r
not r
```
I would really like Lean to do this automatically, but I can't find a way to make it work and had to do it directly myself. Isn't propositional logic completely decidable? So the proofs should be possible to be generated automatically. I mean, the naive algorithm (write the truth table, then convert that to a proof) would give a proof with length exponential in the number of propositions, but considering we would never use propositional logic formulas with more than maybe 4 or 5 different propositions, that's completely not a problem.

**Comment by semorrison** [comment]
I've opened this as a separate issue, and suggested there using the 'congruence closure' tactic.
