### ISSUE TITLE
Substituting for a single term.

### ISSUE THREAD

**Issue by louisanu** [semorrison/2017-summer-students#29]
I got stuck on this trying to show commutativity of multiplication.
Specifically what I was trying to do was show that `one * a + t * a = a + t * a` (because then left distributivity completes the proof).
When I applied the `rw` tactic as below it replaces each instance of `a` with `one*a`. What I want to achieve is only replacing the first instance.

```
theorem mul_comm (a b : xnat) : a * b = b * a :=
begin
induction b with t ht,
    rw [zero_mul, mul_zero],
    unfold mul,
    rw ht,
    have h1 : a + t * a = a + t*a, by refl,
    have h2 : one * a = a, by rw one_mul, 
    rw <- h2 at h1, -- this doesn't work as intended
    admit
end
```

I ended up doing it with `add_cancel_right` instead but I'm still curious as to how I would do it with substitution.
The definitions this builds on are in the xnat.lean file in my folder if anyone wants to have a look.

**Comment by yuxiliu-anu** [comment]
It's not clever. It usually only knows to substitute it at every possible instance. Try this.

```
theorem mul_comm (a b : xnat) : a * b = b * a :=
begin
induction b with t ht,
    rw [zero_mul, mul_zero],
    unfold mul,
    rw ht,
    exact calc 
      a + t * a = one * a + t * a : by rw one_mul
            ... = (one + t) * a : by rw ←left_distrib
            ... = (t + one) * a : by rw add_comm
            ... = succ t * a : by refl
end
```

**Comment by semorrison** [comment]
Oh — sorry I’ve been slow on this. There is a great mechanism for rewriting in particular spots. Look for `conv` in https://github.com/leanprover/lean/blob/master/doc/changes.md.

**Comment by semorrison** [comment]
It’s a relatively recent addition to Lean, so not documented anywhere yet besides the change log.

**Comment by yuxiliu-anu** [comment]
On a high level, what does `conv` do?

**Comment by semorrison** [comment]
`conv` allows you to do pattern matching, and only apply a rewrite or simplification tactic to the subparts of an expression that match the patter, e.g.
 
`conv in (f _ _) { simp }`

which applies `simp` only to the first subexpression of the goal that looks like `f _ _` (i.e. `f` applied to two arguments). You can also use `conv` on hypotheses, rather than the goal, using `conv at h`.

You can also use `conv` to apply a tactic in multiple places, e.g. 

`conv { for (f _ _) {rw [h]} }`

applies `rw [h]` to all subexpressions matching `f _ _`, and

`conv { for (f _ _) [1, 3] {rw [h]}`

applies it to the 1st and 3rd such subexpression.
