### ISSUE TITLE
Bundling

### ISSUE THREAD

**Issue by MitchRowett** [semorrison/2017-summer-students#36]
On Gitter this morning, you and Mario were discussing a third way of bundling group definitions. I didn't quite follow what was suggested - should I be trying this third structure as well?

**Comment by semorrison** [comment]
Hi Mitch, the suggestion was just to use the “subtype” construction,
defining `Subgroup G = { x : set a // is_subgroup x }`. Thinking about
this, I don’t like it much; my experience using subtype is that later your
proofs suffer, because its fields are unhelpfully named “val” and “prop”.

Let’s get ready to send a pull request with unbundled groups. I think for
now there’s no getting around this. Perhaps you could try to define bundled
groups _after_ (rather than in parallel to) unbundled groups, and see if
you can just write one-line proofs in the bundled case, that depend on the
unbundled case.
