### ISSUE TITLE
Parameters in sections

### ISSUE THREAD

**Issue by yuxiliu-anu** [semorrison/2017-summer-students#4]
In the following code, the type of `bar` depends on whether `x, y` are parameters. How does the keyword `parameter` interact with sections?

```
section
parameters (x y : ℕ)
def bar : ℕ → ℕ := λ c, c + x + y
#check bar
end 
#check bar
```

**Comment by semorrison** [comment]
The idea is that when you exit the section in which the parameters are declared, everything magically changes type to take the parameters as explicit arguments.

Essentially it's a trick so that when you have many functions, all taking the same of similar arguments, you can avoid writing out the arguments over and over again.

Once you exit the section, however, the syntactic sugar disappears, and the parameters just need to be provided as arguments.

I just committed a file, showing the output of both `#check` and `#print`. Often `#print` is more useful than `#check`, because it shows you the definition, not just the type. Curiously, even inside the section, while the parameters are available, `#print` shows the type as seen from the outside.
