### ISSUE TITLE
When defining recursive function by a modulo, Lean failed to prove recursive application is decreasing, well founded relation

### ISSUE THREAD

**Issue by yuxiliu-anu** [semorrison/2017-summer-students#6]
```
inductive weekday : Type
| sunday : weekday
| monday : weekday
| tuesday : weekday
| wednesday : weekday
| thursday : weekday
| friday : weekday
| saturday : weekday

namespace weekday -- to save some typing
  def day_of_number : ℕ → weekday 
  | 0 := sunday
  | 1 := monday
  | 2 := tuesday
  | 3 := wednesday
  | 4 := thursday
  | 5 := friday
  | 6 := saturday
  | (n + 7) := day_of_number n
end weekday
```

The last line I want it to be n := day_of_number (n % 7) , but it doesn't compile, since it complained that `failed to prove recursive application is decreasing, well founded relation`

**Comment by louisanu** [comment]
Does lean reduce it in the wrong order perhaps?
What could be happening is that it applies `day_of_number`  before reducing `n%7`. Since it doesn't recognise `(n%7)` as one of the basic cases (0 through 6), `day_of_number (n % 7)` becomes `day_of_number  ((n % 7) % 7)` and this pattern repeats forever.
When I try `#reduce 12` it times out, which somewhat supports this theory.

**Comment by semorrison** [comment]
Can you explain what you mean by `#reduce 12`? For me that just prints `12`.

**Comment by semorrison** [comment]
The problem is that in inductive definitions, Lean needs to be able to prove that it's going 'downhill'
 in some sense, and out of the box it's not being smart enough to know that `n % 7` is 'simpler' than `n`.

I think the right approach here is to just define `day_of_number` in the obvious recursive way, with `(n + 7) := day_of_number n`, and then prove a lemma that says `day_of_number n = day_of_number (n % 7)`.

**Comment by louisanu** [comment]
Oops, I meant `#reduce day_of_number 12`.

**Comment by semorrison** [comment]
I don't actually know how to prove `day_of_number n = day_of_number (n % 7)`. If anyone works it out, I'll be happy to see.

**Comment by yuxiliu-anu** [comment]
I did most of the proof, except instead of 7, I did the case for 2, because that's less tedious.
and except I have left a few admits, because they should be trivial properties of < that I can't find in the library yet.

**Comment by yuxiliu-anu** [comment]
I solved a small version of this. Basically, instead of 7, I did the case for 2. 

It was very tedious, doing low-level proofs mostly about properties of less_than_or_equal and subtractions.

Is there a better way to do it?.
