### ISSUE TITLE
Why keep both dropbox and git? Why not just use git?

### ISSUE THREAD

**Issue by yuxiliu-anu** [semorrison/2017-summer-students#7]
I mean unless you want to keep git strictly as a free forum.

**Comment by semorrison** [comment]
I would be happy to migrate everything over to git. When we met first I thought Dropbox might be easier for everyone, but if everyone agrees I think git is better.

Perhaps everyone can checkout this repository, and move their folder over from Dropbox?

**Comment by semorrison** [comment]
I've added Yuxi and Louis to the repository. Fei and Mitchell, when you get the chance, could you please tell me your github usernames?

**Comment by felicitylu** [comment]
This is Fei. I am good with git!

**Comment by semorrison** [comment]
As we are using git for a learning project, rather than developing software, can I request:

1) Everyone commits more often rather than less often, so I can keep up with what's going on? (In particular, don't worry at all about committing broken or half-working things.)
2) We _don't_ use branches (although it's good to learn how to do this, for real projects you might interact with otherwise), and just keep all our work on the master branch.

If you don't know how to use git yet, now is a great time to learn. There are lots of good tutorials.

**Comment by MitchRowett** [comment]
Using just git is an excellent idea.

**Comment by semorrison** [comment]
Great, I've now added everyone to the repository. Once everyone has successfully added something, I'll close this issue.
